USE [master]
GO
/****** Object:  Database [Etapa2]    Script Date: 01/02/2019 21:38:44 ******/
CREATE DATABASE [Etapa2]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'Etapa2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Etapa2.mdf' , SIZE = 81792KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'Etapa2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Etapa2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Etapa2] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Etapa2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Etapa2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Etapa2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Etapa2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Etapa2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Etapa2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Etapa2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Etapa2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Etapa2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Etapa2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Etapa2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Etapa2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Etapa2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Etapa2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Etapa2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Etapa2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Etapa2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Etapa2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Etapa2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Etapa2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Etapa2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Etapa2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Etapa2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Etapa2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Etapa2] SET  MULTI_USER 
GO
ALTER DATABASE [Etapa2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Etapa2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Etapa2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Etapa2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Etapa2] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Etapa2', N'ON'
GO
ALTER DATABASE [Etapa2] SET QUERY_STORE = OFF
GO
USE [Etapa2]
GO
/****** Object:  Table [dbo].[Datos_Normalizados]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Datos_Normalizados](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DOMINIO] [varchar](50) NULL,
	[DESC_MARCA] [varchar](100) NULL,
	[DESC_MODELO] [varchar](100) NULL,
	[SEGMENTO] [varchar](100) NULL,
	[TRACCION] [varchar](100) NULL,
	[MODELO] [varchar](100) NULL,
	[TIPO] [varchar](100) NULL,
	[DESC_TIPO] [varchar](100) NULL,
	[FEC_INSC] [date] NULL,
	[TITULAR] [varchar](200) NULL,
	[CUIT] [varchar](50) NULL,
	[DIRECCION] [varchar](100) NULL,
	[DESC_PROV] [varchar](100) NULL,
	[COD POSTAL] [varchar](50) NULL,
	[LOCALIDAD] [varchar](100) NULL,
	[CONCESIONARIO] [varchar](100) NULL,
	[LOC_X_CP] [varchar](100) NULL,
	[VENDEDOR] [varchar](100) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DiccionarioModelos]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DiccionarioModelos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[McaMod] [varchar](100) NULL,
	[Cant] [int] NULL,
	[Marca] [varchar](50) NULL,
	[Modelo] [varchar](50) NULL,
 CONSTRAINT [PK_IdMOD] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DiccionarioPrvConces]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DiccionarioPrvConces](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PrvConces] [varchar](100) NULL,
	[Cant] [int] NULL,
	[Provincia] [varchar](100) NULL,
	[Localidad] [varchar](100) NULL,
 CONSTRAINT [PKPrvConces_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NovNormalizado]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NovNormalizado](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ORIGEN] [varchar](50) NULL,
	[DOMINIO] [varchar](50) NULL,
	[MOTOR] [varchar](50) NULL,
	[CHASIS] [varchar](50) NULL,
	[FMM_MTM] [varchar](50) NULL,
	[FABRICA] [varchar](100) NULL,
	[MARCA] [varchar](50) NULL,
	[MODELO] [varchar](100) NULL,
	[TIPO] [varchar](50) NULL,
	[FEC_INSC] [varchar](50) NULL,
	[REGSEC] [varchar](50) NULL,
	[DESC_REG] [varchar](50) NULL,
	[MODO] [varchar](50) NULL,
	[TITULAR] [varchar](200) NULL,
	[CUIT_PREF] [varchar](50) NULL,
	[DIRECCION] [varchar](100) NULL,
	[COD_PRO] [varchar](50) NULL,
	[DESC_PROV] [varchar](100) NULL,
	[COD_DPT] [varchar](50) NULL,
	[DESC_DPT] [varchar](50) NULL,
	[COD_LOC] [varchar](50) NULL,
	[DESC_LOC] [varchar](50) NULL,
	[LOCALIDAD] [varchar](100) NULL,
	[CP] [varchar](50) NULL,
	[ANIO_MOD] [varchar](50) NULL,
	[CODAUTO] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TotalNov]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TotalNov](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ORIGEN] [varchar](50) NULL,
	[DOMINIO] [varchar](50) NULL,
	[MOTOR] [varchar](50) NULL,
	[CHASIS] [varchar](50) NULL,
	[FMM_MTM] [varchar](50) NULL,
	[FABRICA] [varchar](100) NULL,
	[MARCA] [varchar](50) NULL,
	[MODELO] [varchar](100) NULL,
	[TIPO] [varchar](50) NULL,
	[FEC_INSC] [varchar](50) NULL,
	[REGSEC] [varchar](50) NULL,
	[DESC_REG] [varchar](50) NULL,
	[MODO] [varchar](50) NULL,
	[TITULAR] [varchar](200) NULL,
	[CUIT_PREF] [varchar](50) NULL,
	[DIRECCION] [varchar](100) NULL,
	[COD_PRO] [varchar](50) NULL,
	[DESC_PROV] [varchar](100) NULL,
	[COD_DPT] [varchar](50) NULL,
	[DESC_DPT] [varchar](50) NULL,
	[COD_LOC] [varchar](50) NULL,
	[DESC_LOC] [varchar](50) NULL,
	[LOCALIDAD] [varchar](100) NULL,
	[CP] [varchar](50) NULL,
	[ANIO_MOD] [varchar](50) NULL,
	[CODAUTO] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[ActualizarMarcasyModelos]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ActualizarMarcasyModelos]
AS BEGIN
DECLARE @MARCA VARCHAR (50);
DECLARE @MODELO VARCHAR (50);
DECLARE MCAMOD CURSOR FOR SELECT Id,McaMod FROM DiccionarioModelos WHERE Marca IS NULL AND Modelo IS NULL;
OPEN MCAMOD;
DECLARE @MCAMOD VARCHAR (100);
DECLARE @Id INT;
FETCH NEXT FROM MCAMOD
INTO @Id,@MCAMOD
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @MODELO = (SELECT LTRIM(REVERSE(left(REVERSE(@MCAMOD), charindex('-',REVERSE(@MCAMOD))-1))))
	SET @MARCA = @MCAMOD
	SET @MARCA = SUBSTRING(@MCAMOD,1,LEN(@MCAMOD)-(LEN(@MODELO)+1))
	SET @MARCA = (SELECT LTRIM(REVERSE(left(REVERSE(@MARCA), charindex('-',REVERSE(@MARCA))-1))))
	PRINT ''+@Id
	PRINT @MARCA
	PRINT @MODELO
    UPDATE DiccionarioModelos SET Marca=@MARCA, Modelo=@MODELO WHERE Id=@Id
	FETCH NEXT FROM MCAMOD
    INTO @Id,@MCAMOD
END
CLOSE MCAMOD
DEALLOCATE MCAMOD
END
GO
/****** Object:  StoredProcedure [dbo].[ActualizarProvinciasyLocalidades]    Script Date: 01/02/2019 21:38:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ActualizarProvinciasyLocalidades]
AS BEGIN
DECLARE @PROVINCIA VARCHAR (50);
DECLARE @LOC VARCHAR (50);
DECLARE PRVCON CURSOR FOR SELECT Id,PrvConces FROM DiccionarioPrvConces --WHERE Provincia IS NULL AND Localidad IS NULL;
OPEN PRVCON;
DECLARE @PRVCON VARCHAR (100);
DECLARE @Id INT;
FETCH NEXT FROM PRVCON
INTO @Id,@PRVCON
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @LOC = (SELECT LTRIM(REVERSE(left(REVERSE(@PRVCON), charindex('-',REVERSE(@PRVCON))-1))))
	SET @PROVINCIA = @PRVCON
	SET @PROVINCIA = SUBSTRING(@PRVCON,1,LEN(@PRVCON)-(LEN(@LOC)+1))
	SET @PROVINCIA = (SELECT LTRIM(REVERSE(left(REVERSE(@PROVINCIA), charindex('-',REVERSE(@PROVINCIA))-1))))
	PRINT ''+@Id
	PRINT @PRVCON
	PRINT @LOC
    --UPDATE DiccionarioPrvConces SET Localidad=@LOC WHERE Id=@Id
	FETCH NEXT FROM PRVCON
    INTO @Id,@PRVCON
END
CLOSE PRVCON
DEALLOCATE PRVCON
END
GO
USE [master]
GO
ALTER DATABASE [Etapa2] SET  READ_WRITE 
GO
